resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a2d59d68aa8d7f8b162e67b0378e0857ae7adc144286add011c3d44039016652
  name: quay.io/burrsutter/quinoa-wind-turbine
