resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b0ee8f480b7f6f82cbb0628e1cc1c046ff19c5d09a12bae990cc0f06624d2798
  name: quay.io/burrsutter/quinoa-wind-turbine
