resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:66295b388ce6b54910222bc50fe3424f01468ee72f298b6fd8aa53092e7141a5
  name: quay.io/burrsutter/quinoa-wind-turbine
