resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5cbad0ec17a898ef7380442cd9bc8441618cb15a2e3547c9f42e9099a1e3f2e0
  name: quay.io/burrsutter/quinoa-wind-turbine
