resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5c261c7deef3fa3292775ad88aa8070f21a9283afe071d52408da01866bcbec1
  name: quay.io/burrsutter/quinoa-wind-turbine
