resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:28664f3130909de6a3a9e8bc4cd94e4bc6c4cea49771e3ec9d4245962764592a
  name: quay.io/burrsutter/quinoa-wind-turbine
