resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:bb97ffd5d67bf807b9c36d4424e8058534db6ff470f58d90ac572d2f6f6bdeda
  name: quay.io/burrsutter/quinoa-wind-turbine
