resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d61d608e90b4252c7ae78e1b2597e710b33a99b543ef710b0e85f4e808501227
  name: quay.io/burrsutter/quinoa-wind-turbine
