resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a71eeff540eb6ac2ad0f1ea29fd71e8c180d351026e138785004d894d80fa73f
  name: quay.io/burrsutter/quinoa-wind-turbine
