resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:9ca7f652a2e23b722ca3108020b451dd5924ac2e0e071647a7d44aed83c9904f
  name: quay.io/burrsutter/quinoa-wind-turbine
