resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:22d1428baa3267d4a2653f638cac12792c14d2239ec3fb878048de27c85d2664
  name: quay.io/burrsutter/quinoa-wind-turbine
