resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:f7c77e05e3d2a428cff3c9f021ffb72f12337cb72c49b0ce10f55d3d9c56f72e
  name: quay.io/burrsutter/quinoa-wind-turbine
