resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:854d25c98d56702856b0d8a6c165b57a5db81c4b6959206c1dabc24d959e40a9
  name: quay.io/burrsutter/quinoa-wind-turbine
