resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:be30639adac241112fb73d9ffaff11db073a64809a83e995b958561263a39965
  name: quay.io/burrsutter/quinoa-wind-turbine
