resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0cfb40eda54749f28dddd124f09e6bad2a905ffcf279885198391c3f873c80c7
  name: quay.io/burrsutter/quinoa-wind-turbine
