resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:08cf07252d00c5dc698392b8d31f0fee238d04fce9b363d7379ae9fd4f81ce45
  name: quay.io/burrsutter/quinoa-wind-turbine
