resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:9ef3213f5d741ab816da20e86ed61010692b78f077c8e26396e33f345c3d20fd
  name: quay.io/burrsutter/quinoa-wind-turbine
